#!/bin/sh
# Eric McCann (Nuclearmistake) 2014

OUTFD=$(ps | grep -v "grep" | grep -o -E "update_binary(.*)" | cut -d " " -f 3); #BIG props to Chainfire
ui_print() { if [ "$OUTFD" != "" ]; then echo "$0: $*" 1>&$OUTFD; fi; return 0; }

backuptool_header() {
mkdir -p /system/addon.d
cat > /system/addon.d/70-gapps.sh <<\NUKE
#!/sbin/sh
#
# /system/addon.d/70-gapps.sh
# Automatically generated by Nuclearmistake's NuclearFallout gapps install script
#
OUTFD=$(ps | grep -v "grep" | grep -o -E "update_binary(.*)" | cut -d " " -f 3); #BIG props to Chainfire
ui_print() { if [ "$OUTFD" != "" ]; then echo "$0: $*" 1>&$OUTFD; fi; return 0; }

. /tmp/backuptool.functions

list_files() {
cat <<EOF
NUKE
}

backuptool_footer() {
cat >> /system/addon.d/70-gapps.sh <<NUKE
EOF
}

case "\$1" in
  backup)
    list_files | while read FILE DUMMY; do
      backup_file \$S/\$FILE
    done
  ;;
  restore)
    list_files | while read FILE REPLACEMENT; do
      R=""
      [ -n "\$REPLACEMENT" ] && R="\$S/\$REPLACEMENT"
      [ -f "\$C/\$S/\$FILE" ] && restore_file \$S/\$FILE \$R
    done
  ;;
  pre-backup)
    # Stub
  ;;
  post-backup)
    # Stub
  ;;
  pre-restore)
    # Stub
  ;;
  post-restore)
    # Stub
;;
esac
NUKE
}

copy_files() {
  # $1 = temp directory containing files to copy to destination
  # $2 = destination folder
  cd $1
  find . -type d | while read FOLDER; do
    RELATIVE=$(echo $FOLDER | /sbin/busybox sed 's/^\.\///g')
    [ `echo $RELATIVE | wc -c` -gt 0 ] && mkdir -p $2/$RELATIVE
  done
  find . -type f | while read FILE; do
    RELATIVE=$(echo $FILE | /sbin/busybox sed 's/^\.\///g')
    cp $FILE $2/$RELATIVE
    # STRING COMPARE FTW... add files copied to /system to the CM backuptool script
    [ ! $NO_BACKUP ] && echo $RELATIVE >> /system/addon.d/70-gapps.sh
  done
}
